blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('signup/',views.signup_page, name = 'signup_page'),
    path('login/',views.login_page, name='login_page'),
    path('logout/',views.logout_page, name='logout_page'),
    path('profile/',views.profile_page, name='profile_page'),
    path('edit_profile/',views.edit_profile_page, name='edit_profile_page'),
    path('category/<str:slug>/',views.category_list, name='category'),
    path('tags/<str:slug>/',views.tag_list, name='tags'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('polls/',include('polls.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from autoslug import AutoSlugField





class User(AbstractUser):
    email = models.EmailField(null=True,blank=True)
    city = models.CharField(max_length=100,null=True,blank=True)
    state = models.CharField(max_length=50,null=True,blank=True)
    country = models.CharField(max_length=256,null=True,blank=True)
    ph_no = models.IntegerField(null=True,blank=True)
    address = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now=True)
    utimestamp =models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10)
    image = models.FileField(upload_to='user_images/',null=True,blank=True)
    

    def __str__(self):
        return self.email
    
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name')

    def __str__(self): 
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='name')


    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE,null=True,blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    thumbnail = models.ImageField(upload_to='thumbnail/',null=True,blank=True)
    post_image = models.FileField(upload_to='post_images/',null=True,blank=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = AutoSlugField(populate_from='title')


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self): 
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,null=True,blank=True)
    parent = models.ForeignKey('self',related_name="replies", on_delete=models.CASCADE,null=True, blank=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(null=True,blank=True)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now=True)
    utimestamp =models.DateTimeField(auto_now=True)

    def __str__(self): 
        return self.text

blog/forms.py
from django import forms

from .models import Post , User

# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('post_image','thumbnail','title', 'text','category','tags')
# authentication/forms.py



class UserSignUpForm(forms.ModelForm):
	username = forms.CharField(
		required=False,  # Make the username field optional
		widget=forms.TextInput(attrs={'placeholder': 'Username'}),
	
	)
		
	class Meta:
		model = User
		fields = ('first_name','username','password','ph_no','email','city','state','country','image',)


class UserloginForm(forms.ModelForm):
	username = forms.CharField(
	required=False,  # Make the username field optional
	widget=forms.TextInput(attrs={'placeholder': 'Username'}),)
	class Meta:
		model = User
		fields = ('username', 'password')


class ProfileForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['image', 'first_name','ph_no', 'address', 'city', 'state', 'country']
		
class EditProfileForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['image', 'first_name','ph_no', 'address', 'city', 'state', 'country']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required

from django.utils import timezone
from .models import Post,User,Category,Tag,Comment
from django.shortcuts import render, get_object_or_404
from .forms import PostForm , UserSignUpForm  ,UserloginForm , ProfileForm, EditProfileForm
from django.contrib.auth.hashers import make_password
from django. contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse



from .import forms

# Create your views here.


def post_list(request):

    # posts =Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    posts = Post.objects.all()
    return render(request, 'post_list.html', {'posts': posts})


def post_detail(request, slug):

    if request.method == "POST":
        reply = request.POST.get('reply',None)
        parent = request.POST.get('comment',None)
        name = request.POST.get('name',None)
        email= request.POST.get('email',None)
        text = request.POST.get('message',None)
        post = get_object_or_404(Post, slug=slug)
        try:
            comment = Comment.objects.filter(id=int(parent)).first()
            # print(comment, "comment>>>>>>>>>>>>")
            Comment.objects.create(text=reply, post=post,parent=comment,name=name)
        except Exception as e:
            Comment.objects.create(name=name,email=email,text=text, post=post)
        return redirect(reverse('post_detail', kwargs={'slug': post.slug}))        
    else:
        post = get_object_or_404(Post, slug=slug)
        comment = Comment.objects.filter(post=post,  parent__isnull= True)
        Categories = Category.objects.all()
        tags = Tag.objects.all()
    # comments = Comment.objects.all()
    # print(post.post_image,"ddddddddddddddddddddddddddddddddddddd")
        return render(request, 'post_detail.html', {'post': post,'comment':comment,'Categories': Categories,'tags': tags,})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', slug=post.slug)
    else:

        form = PostForm(request.POST)

    return render(request, 'post_edit.html', {'form': form})
def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'post_edit.html', {'form': form})


@csrf_exempt
def signup_page(request):
        form =  UserSignUpForm(request.POST, request.FILES) 
        if request.method == 'POST':

            if form.is_valid():
        
                user = form.save(commit=False)
                user.password = make_password(user.password)
                user.save()

            messages.success(request, 'Account created successfully! You can now log in.')

            return redirect('login_page')
        

        else:
            form =  UserSignUpForm()
                
        return render(request, 'sign_up.html',  context={'form': form})


def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        # print(username,password, "password>>>>>>>>>>>>>>>>>")
        user = authenticate(username=username, password=password)
        # print(user, "user>>>>>>>>>>>>>>>>>>>>>>>>>")
        if user is not None:   
            # print("----====------")
            login(request,user=user)
            messages.success(request,"You are now logged in as {username}")
            return redirect("post_list")
    form = UserloginForm()
    return render(request, "log_in.html", {"form": form})

@login_required
def logout_page(request):
    logout(request)
    return redirect('post_list')


@login_required
def profile_page(request):
    user = request.user
    image = request.user.image
    # print(image,"wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww")
    return render(request, 'profile.html',{'user':user, 'image':image})

def edit_profile_page(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile_page')  # Update this line
    else:
        form = ProfileForm()
    return render(request, 'edit_profile.html', {'form': form})

def category_list(request ,slug):
    categories = get_object_or_404(Category,slug=slug)
    # print( categoryy, "hhhhhhhhhhhhhhhhhhhhhhhhhh")
    posts = Post.objects.filter(category=categories)
    context = {'category': categories,'posts':posts}
    return render(request, 'category_list.html',context)

def tag_list(request,slug):
    tags= get_object_or_404(Tag,slug=slug)
    posts = Post.objects.filter(tags=tags)
    context = {'tags':tags,'posts':posts}
    return render(request,'tag_list.html',context)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Django Girls blog</title>
	<link rel="stylesheet" href="{% static 'css/blog.css' %}">
	<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>

	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">




</head>

<body>
	<!-- <div class="container1" style="width: 100%;  margin: auto;"> -->

	<header class="page-header">
		<div >
			{% if user.is_authenticated %}
			<a href="{% url 'post_new' %}" class="top-menu">
				{% include './icons/file-earmark-plus.svg' %}
			</a>
			{% endif %}
			<div style=" display: flex; justify-content: space-between; padding: 25px; align-items: baseline; ">
				<div style="display: flex;gap: 200px;">
					<h1><a href="/">Django Girls Blog</a></h1>
					<h1><a href="polls/">Django polls</a></h1>
				</div>
				{% if user.is_authenticated %}
				<div style="display: flex;gap: 15px; justify-content: end;">
					<a style="text-decoration: none;" href="{% url 'logout_page' %}"><i
							class="fa-solid fa-right-from-bracket" style="color: #fcfcfd;"></i>&nbsp;&nbsp;<b>log
							out</b></a>
					<a style="text-decoration: none;" href="{% url 'profile_page' %}"><i class="fa-solid fa-user"
							style="color: #fcfcfd;"></i>&nbsp;&nbsp;<b>profile</b></a>
				</div>
				{% else %}
				<div style="display: flex;justify-content: center; ">
					<div style="display: flex;gap: 15px; justify-content: end; margin-top: 30px;">
						<a style="text-decoration: none;" href="{% url 'signup_page' %}"><i
								class="fa-solid fa-user-plus" style="color: #ffffff;"></i>&nbsp;&nbsp;<b>Sign up</b></a>
						<a style="text-decoration: none;" href="{% url 'login_page' %}"><i
								class="fa-solid fa-arrow-right-to-bracket"
								style="color: #f0f2f5;"></i>&nbsp;&nbsp;<b>Log in</b></a>
					</div>
				</div>
				{% endif %}
			</div>
		</div>
	</header>
	<main class="" style=" padding-inline: 150px;">
		<div class="row">
			<div class="col">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</main>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
		integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
		integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
		integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
		crossorigin="anonymous"></script>
</body>

</html>

blog/templates/category_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h1>Posts in category: {{ category.name }}</h1>
<div class="row" style="display: flex; justify-content: center;  flex-wrap: wrap;">
    {% for post in posts %}
        <div class="col-12 col-md-4 pt-5">
            <div class="card" style="box-shadow:4px 4px 5px  #ebebc9; border-radius: 7px; ">
                <div class="img">
                    {% if post.post_image %}
                    <a href="{% url 'post_detail' slug=post.slug %}">
                        <img style="height: 200px; width: 100%; border-radius: 7px;" src="{{ post.post_image.url }}" alt="Profile Picture">
                    </a>
                    {% else %}
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h5>
                    <p class="card-text ;">{{ post.text|truncatechars:100 }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

blog/templates/edit_profile.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
	<title>Edit Profile</title>
</head>

<body>
	{% block content %}
	<div class="PROFILEEDIT" style="display: flex;justify-content: center;">
		<div class="container"
			style="border: 2px solid black; border-radius: 5px; width: auto;padding: 10px;background-color: #fff;">
			<div class="login" style="border: 10px;">
				<h2>Edit Profile</h2>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="edit-profile" style="display: flex;gap: 20px;">
						<div style="display: flex;flex-direction: column;gap: 20px;">
							<label>Image</label>
							<label>first_name</label>
							<label>ph_no</label>
							<label>email</label>
							<label>city</label>
							<label>state</label>
							<label>country</label>
						</div>
						<div style="display: flex;flex-direction: column;gap: 20px;">
							<input type="file" name="image" value="{{ user.image }}" >

							<input type="text" name="username" value="{{ user.first_name }}" maxlength="150" required=""
								id="id_first_name">
							<input type="text" name="ph_no" value="{{ user.ph_no }}" maxlength="30" id="id_ph_no">
							<input type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email">
							<input type="text" name="city" value="{{ user.city }}" maxlength="400" id="id_city">
							<input type="state" name="state" value="{{ user.state }}" maxlength="254" id="id_state">
							<input type="country" name="country" value="{{ user.country }}" maxlength="254"
								id="id_country">
						</div>
					</div>
					<div style="display: flex;justify-content: center;padding-top:15px;">
						<button style="width: 100px;padding: 5px;background-color: #C25100;color: white;border-radius: 20px;border-color: #C25100;" type="submit">Submit</button>
					</div>
				</form>
			</div>
		</div>
	</div>
	{% endblock %}
</body>

</html>

blog/templates/log_in.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>

</head>

<body>
    {% block content %}
    <div class="LOGIN" style="display: flex;justify-content: center;">
        <div class="container"
            style="border: 2px solid black; border-radius: 5px; width: auto;padding: 10px;background-color: #fff;">
            <div class="login" style="border: 10px;">
                <h2>Login</h2>
                <form method="post">
                    {% csrf_token %}
                    <div style="justify-content: space-between;">
                        {{ form.as_p }}
                    </div>
                    <div style="display: flex; justify-content: center;">
                        <button
                            style="text-align: center; padding: 5px;background-color: #C25100; width: 100px; color: white;border-radius: 20px;border-color: #C25100;"
                            type="submit">Log in</button>
                    </div>
            </div>

            </form>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
        <p>
            <a href="/">Back to home</a>
        </p>
    </div>



    {% endblock %}

</body>

</html>

blog/templates/post_detail.html
{% extends 'base.html' %} {% block content %}
<div
  style="display: flex; justify-content: space-between; width: 100%; gap: 25px"
>
  <article class="post">
    <div style="display: flex; justify-content: space-between">
      <div>
        <div
          style="
            display: flex;
            justify-content: left;
            margin-bottom: 30px;
            align-items: center;
            width: 100%;
          "
        >
          <div>
            <img
              style="border-radius: 50%; height: 60px; width: 60px"
              src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% else %} {% endif %} "
              alt="..."
            />
          </div>
          <div>
            <h2 style="display: flex; justify-content: left">
              &nbsp;{{ post.title }}
            </h2>
          </div>
        </div>
      </div>

      <div>
        {% if post.published_date %}
        <time class="date">
          {{ post.published_date }}
          <a
            class="btn btn-secondary"
            href="{% url 'post_edit' slug=post.slug %}"
          >
            {% include './icons/pencil-fill.svg' %}
          </a>
          {% endif %}
        </time>
      </div>
    </div>

    <a href="{% url 'post_detail' slug=post.slug %}">
      <img
        style="height: 400px; width: 100%; border-radius: 10px"
        src="{{ post.post_image.url }}"
        alt="Profile Picture"
      />
    </a>
    <p>
      <b style="display: flex; justify-content: space-between">
        <span>
          Category:-
          <a
            style="text-decoration: none"
            href="{% url 'category' slug=post.category.slug %}"
            >{{ post.category }}</a
          >
        </span>
        <span> Author:- {{ post.author }} </span>
      </b>
    </p>
    <p>{{ post.text|linebreaksbr }}</p>
    <b
      >Tags :- {% for tag in post.tags.all %}
      <a style="text-decoration: none" href="{% url 'tags' slug=tag.slug %}"
        >{{ tag }} |</a
      >
      {% endfor %}
    </b>
    <aside class="actions">{% if user.is_authenticated %} {% endif %}</aside>
  </article>
  <div
    style="
      border: 1px solid black;
      border-radius: 5px;
      height: 100%;
      padding: 20px;
      width: 200px;
    "
  >
    <h3>Categories</h3>
    <ul>
      {% for category in Categories %}
      <li>
        <a
          style="text-decoration: none"
          href="{% url 'category' category.slug %}"
          >{{ category.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
    <h3>Tags</h3>
    <ul>
      {% for tag in tags %}
      <li>
        <a style="text-decoration: none" href="{% url 'tags' tag.slug %}"
          >{{ tag.name }}</a
        >
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

<div>
  <form method="post">
    {% csrf_token %}
    <div
      style="
        display: flex;
        flex-direction: column;
        border: 1px solid grey;
        border-radius: 10px;
        width: 300px;
        padding: 10px;
        margin: 5px;
      "
    >
      <h2>Comments</h2>
      <label for="name">Name</label>
      <input type="text" name="name" id="id_name" />
      <label for="email">Email</label>
      <input type="email" name="email" id="id_email" />
      <label for="message">message</label>
      <textarea type="text" name="message" id="id_message"></textarea>
      <div
        style="
          margin-top: 10px;
          align-items: center;
          display: flex;
          justify-content: center;
        "
      >
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
</div>
<div style="display: flex; flex-direction: column; gap: 10px;">
  {% if not comment %}
   not comment yet....
	{% else %} 
  {% for comment in comment %}
  <div style="display: flex; flex-direction: column">
    <p style="font-weight: 700; margin: 0px">{{ comment.name }}</p>
    <div style="display: flex; gap: 10px">
      <p style="margin: 0px">- {{ comment.text }}</p>
      <div>
        <form method="post">
          {% csrf_token %}
		  
        <div
            style="
              display: flex;
              flex-direction: column;
              border-radius: 10px;
              width: 200px;
              padding: 10px;
              margin: 5px;
			  gap: 10px;
            "
          >
            <h2>reply</h2>
            <label for="name">Name</label>
            <input type="text" name="name" id="id_name" />
            <label for="email">Email</label>
            <input type="email" name="email" id="id_email" />
            <label for="message">message</label>
            <input type="hidden" name="comment" value="{{ comment.id }}" />
            <textarea name="reply"></textarea>
            <div
              style="
                margin-top: 10px;
                align-items: center;
                display: flex;
                justify-content: center;
              "
            >
              <button type="submit" class="btn btn-primary">reply</button>
            </div>
		</div>

        </form>
      </div>
    </div>

	  <div style="display: flex;flex-direction: column;">
	{% for reply in comment.replies.all %}
	<div style="display: flex;flex-direction: column;">
      <p style="font-weight: 660; margin: 0px">{{ reply.name }}</p>
      <span style="overflow: hidden; width: max- content">
        - {{ reply.text }}
      </span><br>
	</div>
      {% endfor %}
	</div>
  </div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

blog/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/post_list.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<style>
		
	</style>
</head>
<body>
	<div class="row" style="display: flex; flex-wrap: wrap;">
		{% for post in posts %}
			<div class="col-12 col-md-4 pt-5">
				<div class="card" style="box-shadow:4px 4px 5px  #ebebc9; border-radius: 7px; ">
					<div class="img">
						<a href="{% url 'post_detail' post.slug %}">
						<img style="height: 200px; width: 100%; border-radius: 7px;" src="{% if post.post_image %}{{ post.post_image.url }}{% else %}{% endif %}" alt="Profile Picture">
						</a>
					</div>
					<div class="card-body">
						<h5 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h5>
						<p>Category:- <a href="{% url 'category' slug=post.category.slug %}">{{post.category}}</a></p>
						<p>Tag:-
							{% for tag in post.tags.all %} 
							<a style="text-decoration: none;" href="{% url 'tags' slug=tag.slug %}">{{tag}} |</a>
							{% endfor %}
						</p>
						<p class="card-text ;">{{ post.text|truncatechars:150 }}</p>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	</body>


</html>
{% endblock %}

blog/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Profile Page{% endblock title %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>profile</title>
        <style>

    
            
            /* body {
                    height: 100%;
                    margin: 0;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    font-family: Arial, sans-serif;
            } */
            .profile {
                text-align: center;
                border: 2px solid #ddd;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                max-width: 400px;
                width: 100%;
                background-color: #fff;
                
            }

            h1 {
                font-size: 24px;
                margin-bottom: 15px;
            }

            img {
                margin-bottom: 20px;
                text-align: left;
            }

            p {
            margin: 8px 0;
            font-size: 16px;
            color: #333;
            text-align: left;
            }

        </style>
    </head>
    <body style="display: block; align-items: center;">
        <div class="kkkk" style="display: flex; justify-content: center;">
        <div class="profile">
            <h1>User Profile {{User.username}}</h1>
            <div class="img">
                {% if user.image %}
                    <img style="height: 100px; width: 100px;" src="{{ user.image.url }}" alt="Profile Picture">
                {% else %}
                    <img style="height: 100px; width: 100px;" src="{% static 'images/default-profile.png' %}" alt="Default Profile Picture">
                {% endif %}
            </div>
                <p>{{ user.first_name }}</p>
                <p>{{ user.ph_no }}</p>
                <p>{{ user.email }}</p>
                <p>{{ user.city }}</p>
                <p>{{ user.state }}</p>
                <p>{{ user.country }}</p>
            <div>
                <button><a  style="text-decoration: none;" href="{% url 'edit_profile_page' %}"><i class="fa-solid fa-pencil" style="color: #4913ec ;"></i>&nbsp;&nbsp;edit profile</button></a>
            </div>
            </div>

        </div>
    </body>
    </html>
{% endblock content %}

blog/templates/sign_up.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>

{% block content %}
<div  style="display: flex;justify-content: center;">
    <div class="form-container" style="border: 2px solid rgb(73, 67, 67); border-radius: 10px; width: 500px; padding: 10px; background-color: white;">
        <h2>Sign Up</h2>
        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <br>
                <div class="form-group" style="display: flex; justify-content: space-between;">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <br>
            <div style="display: flex;justify-content: center;">
                <button style="width: 100px;padding: 5px;background-color: #C25100;color: white;border-radius: 20px;border-color: #C25100;" type="submit">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

blog/templates/tag_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h1>Posts in tags: {{ tags.name }}</h1>
<div class="row" style="display: flex; justify-content: center;  flex-wrap: wrap;">
    {% for post in posts %}
        <div class="col-12 col-md-4 pt-5">
            <div class="card" style="box-shadow:4px 4px 5px  #ebebc9; border-radius: 7px; ">
                <div class="img">
                    {% if post.post_image %}
                    <a href="{% url 'post_detail' slug=post.slug %}">
                        <img style="height: 200px; width: 100%; border-radius: 7px;" src="{{ post.post_image.url }}" alt="Profile Picture">
                    </a>
                    {% else %}
                    {% endif %}
                </div>
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h5>
                    <p class="card-text ;">{{ post.text|truncatechars:200 }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}